/**
 * Fulfillment From: country and city options.
 * Country selection first, then city selection based on country.
 * Generated from GeoNames (https://www.geonames.org/). Run: node scripts/load-geonames.mjs
 */

export const FULFILLMENT_COUNTRIES = [
  "Afghanistan",
  "Aland Islands",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bonaire, Saint Eustatius and Saba",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "British Virgin Islands",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos Islands",
  "Colombia",
  "Comoros",
  "Cook Islands",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Curacao",
  "Cyprus",
  "Czechia",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Falkland Islands",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands Antilles",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "North Korea",
  "North Macedonia",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Other",
  "Pakistan",
  "Palau",
  "Palestinian Territory",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Republic of the Congo",
  "Reunion",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Barthelemy",
  "Saint Helena",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Serbia and Montenegro",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "The Netherlands",
  "Timor Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "U.S. Virgin Islands",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "United States Minor Outlying Islands",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican",
  "Venezuela",
  "Vietnam",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
] as const;

export type FulfillmentCountry = (typeof FULFILLMENT_COUNTRIES)[number];

export const FULFILLMENT_CITIES_BY_COUNTRY: Record<string, string[]> = {
  "Afghanistan": [
    "Aībak",
    "Asadābād",
    "Bāmyān",
    "Bāzārak",
    "Charikar",
    "Farah",
    "Fayzabad",
    "Gardez",
    "Ghazni",
    "Herāt",
    "Jalālābād",
    "Kabul",
    "Kandahār",
    "Khōst",
    "Kunduz",
    "Lashkar Gāh",
    "Maymana",
    "Mazār-e Sharīf",
    "Mehtar Lām",
    "Nīlī",
    "Pul-e Khumrī",
    "Sar-e Pul",
    "Shibirghān",
    "Taloqan",
    "Zaranj",
    "Other",
  ],
  "Aland Islands": [
    "Mariehamn",
    "Other",
  ],
  "Albania": [
    "Berat",
    "Durrës",
    "Elbasan",
    "Fier",
    "Gjirokastër",
    "Korçë",
    "Kukës",
    "Lezhë",
    "Shkodër",
    "Tirana",
    "Vlorë",
    "Other",
  ],
  "Algeria": [
    "Adrar",
    "Aïn Defla",
    "Aïn Temouchent",
    "Algiers",
    "Annaba",
    "Batna City",
    "Béchar",
    "Béjaïa",
    "Biskra",
    "Blida",
    "Bordj Bou Arreridj",
    "Bouïra",
    "Boumerdas",
    "Chlef",
    "Constantine",
    "Djelfa",
    "El Bayadh",
    "El Meghaïer",
    "El Menia",
    "El Oued",
    "Ghardaïa",
    "Guelma",
    "Jijel",
    "Khenchela",
    "Laghouat",
    "M'Sila",
    "Mascara",
    "Médéa",
    "Mila",
    "Mostaganem",
    "Oran",
    "Ouargla",
    "Ouled Djellal",
    "Oum el Bouaghi",
    "Relizane",
    "Saïda",
    "Sétif",
    "Sidi Bel Abbes",
    "Skikda",
    "Souk Ahras",
    "Tamanghasset",
    "Tébessa",
    "Tiaret",
    "Timimoun",
    "Tindouf",
    "Tipasa",
    "Tissemsilt",
    "Tizi Ouzou",
    "Tlemcen",
    "Touggourt",
    "Other",
  ],
  "American Samoa": [
    "Pago Pago",
    "Other",
  ],
  "Andorra": [
    "Andorra la Vella",
    "les Escaldes",
    "Other",
  ],
  "Angola": [
    "Benguela",
    "Cabinda",
    "Caxito",
    "Cuíto",
    "Dundo",
    "Huambo",
    "Luanda",
    "Lubango",
    "Luena",
    "Malanje",
    "Mbanza Kongo",
    "Menongue",
    "Mossamedes",
    "N'dalatando",
    "Ondjiva",
    "Saurimo",
    "Sumbe",
    "Uíge",
    "Other",
  ],
  "Anguilla": [
    "The Valley",
    "Other",
  ],
  "Antarctica": [
    "Other",
    "Other",
  ],
  "Antigua and Barbuda": [
    "Saint John’s",
    "Other",
  ],
  "Argentina": [
    "Buenos Aires",
    "Catamarca",
    "Córdoba",
    "Corrientes",
    "Formosa",
    "La Plata",
    "La Rioja",
    "Mendoza",
    "Neuquén",
    "Paraná",
    "Posadas",
    "Rawson",
    "Resistencia",
    "Río Gallegos",
    "Salta",
    "San Juan",
    "San Luis",
    "San Miguel de Tucumán",
    "San Salvador de Jujuy",
    "Santa Fe",
    "Santa Rosa",
    "Santiago del Estero",
    "Ushuaia",
    "Viedma",
    "Other",
  ],
  "Armenia": [
    "Armavir",
    "Artashat",
    "Ashtarak",
    "Gavar",
    "Gyumri",
    "Hrazdan",
    "Ijevan",
    "Kapan",
    "Vanadzor",
    "Yerevan",
    "Other",
  ],
  "Aruba": [
    "Oranjestad",
    "Other",
  ],
  "Australia": [
    "Adelaide",
    "Brisbane",
    "Canberra",
    "Darwin",
    "Hobart",
    "Melbourne",
    "Perth",
    "Sydney",
    "Other",
  ],
  "Austria": [
    "Bregenz",
    "Graz",
    "Innsbruck",
    "Klagenfurt am Wörthersee",
    "Linz",
    "Salzburg",
    "Sankt Pölten",
    "Vienna",
    "Other",
  ],
  "Azerbaijan": [
    "Ağdam",
    "Ağdaş",
    "Agdzhabedy",
    "Aghsu",
    "Astara",
    "Baku",
    "Barda",
    "Beylagan",
    "Divichibazar",
    "Fizuli",
    "Ganja",
    "Göyçay",
    "Göygöl",
    "Hacıqabul",
    "Imishli",
    "İsmayıllı",
    "Jalilabad",
    "Khirdalan",
    "Kyurdarmir",
    "Lankaran",
    "Lerik",
    "Mingachevir",
    "Naxçıvan",
    "Neftçala",
    "Pushkino",
    "Qazax",
    "Quba",
    "Qusar",
    "Saatlı",
    "Sabirabad",
    "Salyan",
    "Shamakhi",
    "Shamkhor",
    "Sheki",
    "Şirvan",
    "Sumqayıt",
    "Şuşa",
    "Terter",
    "Tovuz",
    "Ujar",
    "Xaçmaz",
    "Yevlakh",
    "Zaqatala",
    "Other",
  ],
  "Bahamas": [
    "Freeport",
    "Nassau",
    "Other",
  ],
  "Bahrain": [
    "Manama",
    "Other",
  ],
  "Bangladesh": [
    "Barishal",
    "Chattogram",
    "Dhaka",
    "Khulna",
    "Mymensingh",
    "Rajshahi",
    "Rangpur",
    "Sylhet",
    "Other",
  ],
  "Barbados": [
    "Bridgetown",
    "Other",
  ],
  "Belarus": [
    "Brest",
    "Homyel'",
    "Hrodna",
    "Mahilyow",
    "Minsk",
    "Vitebsk",
    "Other",
  ],
  "Belgium": [
    "Brussels",
    "Namur",
    "Other",
  ],
  "Belize": [
    "Belize City",
    "Belmopan",
    "Orange Walk",
    "Other",
  ],
  "Benin": [
    "Abomey",
    "Allada",
    "Aplahoué",
    "Dassa-Zoumè",
    "Djougou",
    "Kandi",
    "Lokossa",
    "Natitingou",
    "Parakou",
    "Porto-Novo",
    "Other",
  ],
  "Bermuda": [
    "Hamilton",
    "Other",
  ],
  "Bhutan": [
    "Punākha",
    "Thimphu",
    "Tsirang",
    "Other",
  ],
  "Bolivia": [
    "Cobija",
    "Cochabamba",
    "Oruro",
    "Potosí",
    "Santa Cruz de la Sierra",
    "Sucre",
    "Tarija",
    "Trinidad",
    "Other",
  ],
  "Bonaire, Saint Eustatius and Saba": [
    "Kralendijk",
    "Other",
  ],
  "Bosnia and Herzegovina": [
    "Banja Luka",
    "Brčko",
    "Sarajevo",
    "Other",
  ],
  "Botswana": [
    "Francistown",
    "Gaborone",
    "Ghanzi",
    "Jwaneng",
    "Kanye",
    "Maun",
    "Mochudi",
    "Molepolole",
    "Ramotswa",
    "Serowe",
    "Other",
  ],
  "Bouvet Island": [
    "Other",
    "Other",
  ],
  "Brazil": [
    "Aracaju",
    "Belém",
    "Belo Horizonte",
    "Boa Vista",
    "Brasília",
    "Campo Grande",
    "Cuiabá",
    "Curitiba",
    "Florianópolis",
    "Fortaleza",
    "Goiânia",
    "João Pessoa",
    "Macapá",
    "Maceió",
    "Manaus",
    "Natal",
    "Palmas",
    "Porto Alegre",
    "Porto Velho",
    "Recife",
    "Rio Branco",
    "Rio de Janeiro",
    "Salvador",
    "São Luís",
    "São Paulo",
    "Teresina",
    "Vitória",
    "Other",
  ],
  "British Indian Ocean Territory": [
    "Other",
    "Other",
  ],
  "British Virgin Islands": [
    "Road Town",
    "Other",
  ],
  "Brunei": [
    "Bandar Seri Begawan",
    "Kuala Belait",
    "Tutong",
    "Other",
  ],
  "Bulgaria": [
    "Blagoevgrad",
    "Burgas",
    "Dobrich",
    "Gabrovo",
    "Haskovo",
    "Kardzhali",
    "Kyustendil",
    "Lovech",
    "Montana",
    "Pazardzhik",
    "Pernik",
    "Pleven",
    "Plovdiv",
    "Razgrad",
    "Ruse",
    "Shumen",
    "Silistra",
    "Sliven",
    "Smolyan",
    "Sofia",
    "Stara Zagora",
    "Targovishte",
    "Varna",
    "Veliko Tŭrnovo",
    "Vidin",
    "Vratsa",
    "Yambol",
    "Other",
  ],
  "Burkina Faso": [
    "Banfora",
    "Bobo-Dioulasso",
    "Dédougou",
    "Dori",
    "Fada N'gourma",
    "Kaya",
    "Koudougou",
    "Manga",
    "Ouagadougou",
    "Ouahigouya",
    "Tenkodogo",
    "Ziniaré",
    "Other",
  ],
  "Burundi": [
    "Bubanza",
    "Bujumbura",
    "Cibitoke",
    "Gitega",
    "Kayanza",
    "Kirundo",
    "Ngozi",
    "Rumonge",
    "Other",
  ],
  "Cabo Verde": [
    "Assomada",
    "Espargos",
    "Mindelo",
    "Praia",
    "Other",
  ],
  "Cambodia": [
    "Banlung",
    "Battambang",
    "Kampong Cham",
    "Kampong Chhnang",
    "Kampong Speu",
    "Kampong Thom",
    "Kampot",
    "Koh Kong",
    "Kratié",
    "Pailin",
    "Phnom Penh",
    "Prey Veng",
    "Pursat",
    "Samraong",
    "Siem Reap",
    "Sihanoukville",
    "Sisophon",
    "Stung Treng",
    "Suong",
    "Svay Rieng",
    "Ta Khmau",
    "Takeo",
    "Tbeng Meanchey",
    "Other",
  ],
  "Cameroon": [
    "Bafoussam",
    "Bamenda",
    "Bertoua",
    "Buea",
    "Douala",
    "Ébolowa",
    "Garoua",
    "Maroua",
    "Ngaoundéré",
    "Yaoundé",
    "Other",
  ],
  "Canada": [
    "Charlottetown",
    "Edmonton",
    "Fredericton",
    "Halifax",
    "Ottawa",
    "Québec",
    "Regina",
    "St. John's",
    "Toronto",
    "Victoria",
    "Whitehorse",
    "Winnipeg",
    "Yellowknife",
    "Other",
  ],
  "Cayman Islands": [
    "George Town",
    "West Bay",
    "Other",
  ],
  "Central African Republic": [
    "Bambari",
    "Bangassou",
    "Bangui",
    "Batangafo",
    "Berbérati",
    "Bimbo",
    "Bossangoa",
    "Bouar",
    "Bozoum",
    "Bria",
    "Carnot",
    "Kaga-Bandoro",
    "Mbaïki",
    "Ndélé",
    "Nola",
    "Paoua",
    "Sibut",
    "Other",
  ],
  "Chad": [
    "Abéché",
    "Am Timan",
    "Amdjarass",
    "Ati",
    "Biltine",
    "Bol",
    "Bongor",
    "Doba",
    "Fada",
    "Faya-Largeau",
    "Goz Beida",
    "Koumra",
    "Laï",
    "Mao",
    "Massakory",
    "Mongo",
    "Moundou",
    "Moussoro",
    "N'Djamena",
    "Pala",
    "Sarh",
    "Other",
  ],
  "Chile": [
    "Antofagasta",
    "Arica",
    "Chillán",
    "Concepción",
    "Copiapó",
    "Coyhaique",
    "Iquique",
    "La Serena",
    "Puerto Montt",
    "Punta Arenas",
    "Rancagua",
    "Santiago",
    "Talca",
    "Temuco",
    "Valdivia",
    "Valparaíso",
    "Other",
  ],
  "China": [
    "Beijing",
    "Changchun",
    "Changsha",
    "Chengdu",
    "Chongqing",
    "Fuzhou",
    "Guangzhou",
    "Guiyang",
    "Haikou",
    "Hangzhou",
    "Harbin",
    "Hefei",
    "Hohhot",
    "Jinan",
    "Kunming",
    "Lanzhou",
    "Lhasa",
    "Nanchang",
    "Nanjing",
    "Nanning",
    "Shanghai",
    "Shenyang",
    "Shijiazhuang",
    "Taiyuan",
    "Tianjin",
    "Ürümqi",
    "Wuhan",
    "Xi’an",
    "Xining",
    "Yinchuan",
    "Zhengzhou",
    "Other",
  ],
  "Christmas Island": [
    "Flying Fish Cove",
    "Other",
  ],
  "Cocos Islands": [
    "West Island",
    "Other",
  ],
  "Colombia": [
    "Arauca",
    "Armenia",
    "Barranquilla",
    "Bogotá",
    "Bucaramanga",
    "Cali",
    "Cartagena",
    "Cúcuta",
    "Florencia",
    "Ibagué",
    "Leticia",
    "Manizales",
    "Medellín",
    "Mitú",
    "Mocoa",
    "Montería",
    "Neiva",
    "Pasto",
    "Pereira",
    "Popayán",
    "Puerto Carreño",
    "Quibdó",
    "Riohacha",
    "San Andrés",
    "San José del Guaviare",
    "Santa Marta",
    "Sincelejo",
    "Tunja",
    "Valledupar",
    "Villavicencio",
    "Yopal",
    "Other",
  ],
  "Comoros": [
    "Fomboni",
    "Moroni",
    "Moutsamoudou",
    "Other",
  ],
  "Cook Islands": [
    "Avarua",
    "Other",
  ],
  "Costa Rica": [
    "Alajuela",
    "Cartago",
    "Heredia",
    "Liberia",
    "Limón",
    "Puntarenas",
    "San José",
    "Other",
  ],
  "Croatia": [
    "Bjelovar",
    "Čakovec",
    "Dubrovnik",
    "Karlovac",
    "Koprivnica",
    "Osijek",
    "Požega",
    "Rijeka",
    "Šibenik",
    "Sisak",
    "Slavonski Brod",
    "Split",
    "Varaždin",
    "Vukovar",
    "Zadar",
    "Zagreb",
    "Other",
  ],
  "Cuba": [
    "Artemisa",
    "Bayamo",
    "Camagüey",
    "Ciego de Ávila",
    "Cienfuegos",
    "Guantánamo",
    "Havana",
    "Holguín",
    "Las Tunas",
    "Matanzas",
    "Nueva Gerona",
    "Pinar del Río",
    "San José de las Lajas",
    "Sancti Spíritus",
    "Santa Clara",
    "Santiago de Cuba",
    "Other",
  ],
  "Curacao": [
    "Willemstad",
    "Other",
  ],
  "Cyprus": [
    "Famagusta",
    "Kyrenia",
    "Larnaca",
    "Limassol",
    "Nicosia",
    "Paphos",
    "Other",
  ],
  "Czechia": [
    "Brno",
    "České Budějovice",
    "Hradec Králové",
    "Jihlava",
    "Karlovy Vary",
    "Liberec",
    "Olomouc",
    "Ostrava",
    "Pardubice",
    "Pilsen",
    "Prague",
    "Ústí nad Labem",
    "Zlín",
    "Other",
  ],
  "Democratic Republic of the Congo": [
    "Bandundu Province",
    "Boende",
    "Bukavu",
    "Bunia",
    "Buta",
    "Gbadolite",
    "Gemena",
    "Goma",
    "Inongo",
    "Isiro",
    "Kamina",
    "Kananga",
    "Kindu",
    "Kinshasa",
    "Kisangani",
    "Lubumbashi",
    "Lusambo",
    "Matadi",
    "Mbandaka",
    "Mbuji-Mayi",
    "Other",
  ],
  "Denmark": [
    "Aalborg",
    "Copenhagen",
    "Hillerød",
    "Vejle",
    "Viborg",
    "Other",
  ],
  "Djibouti": [
    "Ali Sabih",
    "Arta",
    "Dikhil",
    "Djibouti",
    "Obock",
    "Tadjoura",
    "Other",
  ],
  "Dominica": [
    "Roseau",
    "Other",
  ],
  "Dominican Republic": [
    "Azua",
    "Baní",
    "Bonao",
    "Cotuí",
    "Dajabón",
    "Hato Mayor del Rey",
    "La Romana",
    "La Vega",
    "Mao",
    "Moca",
    "Monte Plata",
    "Nagua",
    "Neiba",
    "Puerto Plata",
    "Salcedo",
    "Salvaleón de Higüey",
    "San Cristóbal",
    "San Fernando de Monte Cristi",
    "San Francisco de Macorís",
    "San Ignacio de Sabaneta",
    "San José de Ocoa",
    "San Juan de la Maguana",
    "San Pedro de Macorís",
    "Santa Cruz de Barahona",
    "Santa Cruz de El Seibo",
    "Santiago de los Caballeros",
    "Santo Domingo",
    "Santo Domingo Este",
    "Other",
  ],
  "Ecuador": [
    "Ambato",
    "Azogues",
    "Babahoyo",
    "Cuenca",
    "Esmeraldas",
    "Guaranda",
    "Guayaquil",
    "Ibarra",
    "Latacunga",
    "Loja",
    "Macas",
    "Machala",
    "Nueva Loja",
    "Portoviejo",
    "Puerto Francisco de Orellana",
    "Puyo",
    "Quito",
    "Riobamba",
    "Santa Elena",
    "Santo Domingo de los Colorados",
    "Tena",
    "Tulcán",
    "Zamora",
    "Other",
  ],
  "Egypt": [
    "Al Fayyum",
    "Al Khārjah",
    "Al Mansurah",
    "Alexandria",
    "Arīsh",
    "Assiut",
    "Aswān",
    "Banhā",
    "Banī Suwayf",
    "Cairo",
    "Damanhur",
    "Damietta",
    "El-Tor",
    "Giza",
    "Hurghada",
    "Ismailia",
    "Kafr ash Shaykh",
    "Luxor",
    "Marsá Maţrūḩ",
    "Minya",
    "Port Said",
    "Qina",
    "Shibīn al Kawm",
    "Sohag",
    "Suez",
    "Tanta",
    "Zagazig",
    "Other",
  ],
  "El Salvador": [
    "Ahuachapán",
    "Chalatenango",
    "Cojutepeque",
    "La Unión",
    "San Francisco",
    "San Miguel",
    "San Salvador",
    "San Vicente",
    "Santa Ana",
    "Santa Tecla",
    "Sensuntepeque",
    "Sonsonate",
    "Usulután",
    "Zacatecoluca",
    "Other",
  ],
  "Equatorial Guinea": [
    "Bata",
    "Ciudad de la Paz",
    "Ebebiyin",
    "Malabo",
    "Other",
  ],
  "Eritrea": [
    "Asmara",
    "Assab",
    "Barentu",
    "Keren",
    "Massawa",
    "Mendefera",
    "Other",
  ],
  "Estonia": [
    "Pärnu",
    "Tallinn",
    "Tartu",
    "Viljandi",
    "Other",
  ],
  "Eswatini": [
    "Manzini",
    "Mbabane",
    "Other",
  ],
  "Ethiopia": [
    "Addis Ababa",
    "Āsosa",
    "Awasa",
    "Bahir Dar",
    "Bonga",
    "Dire Dawa",
    "Gambēla",
    "Harar",
    "Hosa’ina",
    "Jijiga",
    "Mek'ele",
    "Samara",
    "Sodo",
    "Other",
  ],
  "Falkland Islands": [
    "Stanley",
    "Other",
  ],
  "Faroe Islands": [
    "Tórshavn",
    "Other",
  ],
  "Fiji": [
    "Labasa",
    "Lautoka",
    "Suva",
    "Other",
  ],
  "Finland": [
    "Hämeenlinna",
    "Helsinki",
    "Joensuu",
    "Jyväskylä",
    "Kajaani",
    "Kokkola",
    "Kouvola",
    "Kuopio",
    "Lahti",
    "Lappeenranta",
    "Mikkeli",
    "Oulu",
    "Pori",
    "Rovaniemi",
    "Seinäjoki",
    "Tampere",
    "Turku",
    "Vaasa",
    "Other",
  ],
  "France": [
    "Ajaccio",
    "Bordeaux",
    "Dijon",
    "Lille",
    "Lyon",
    "Marseille",
    "Nantes",
    "Orléans",
    "Paris",
    "Rennes",
    "Rouen",
    "Strasbourg",
    "Toulouse",
    "Other",
  ],
  "French Guiana": [
    "Cayenne",
    "Other",
  ],
  "French Polynesia": [
    "Papeete",
    "Other",
  ],
  "French Southern Territories": [
    "Port-aux-Français",
    "Other",
  ],
  "Gabon": [
    "Franceville",
    "Koulamoutou",
    "Lambaréné",
    "Libreville",
    "Makokou",
    "Mouila",
    "Oyem",
    "Port-Gentil",
    "Tchibanga",
    "Other",
  ],
  "Gambia": [
    "Banjul",
    "Brikama",
    "Other",
  ],
  "Georgia": [
    "Akhaltsikhe",
    "Batumi",
    "Gori",
    "Kutaisi",
    "Rustavi",
    "Sokhumi",
    "Tbilisi",
    "Telavi",
    "Zugdidi",
    "Other",
  ],
  "Germany": [
    "Berlin",
    "Bremen",
    "Dresden",
    "Düsseldorf",
    "Erfurt",
    "Hamburg",
    "Hannover",
    "Kiel",
    "Magdeburg",
    "Mainz",
    "Munich",
    "Potsdam",
    "Saarbrücken",
    "Schwerin",
    "Stuttgart",
    "Wiesbaden",
    "Other",
  ],
  "Ghana": [
    "Accra",
    "Bolgatanga",
    "Cape Coast",
    "Dambai",
    "Damongo",
    "Goaso",
    "Ho",
    "Koforidua",
    "Kumasi",
    "Nalerigu",
    "Sekondi-Takoradi",
    "Sunyani",
    "Tamale",
    "Techiman",
    "Wa",
    "Other",
  ],
  "Gibraltar": [
    "Gibraltar",
    "Other",
  ],
  "Greece": [
    "Athens",
    "Corfu",
    "Ioánnina",
    "Irákleion",
    "Komotiní",
    "Kozáni",
    "Lamía",
    "Lárisa",
    "Mytilene",
    "Pátra",
    "Thessaloníki",
    "Trípoli",
    "Other",
  ],
  "Greenland": [
    "Nuuk",
    "Other",
  ],
  "Grenada": [
    "Saint George's",
    "Other",
  ],
  "Guadeloupe": [
    "Basse-Terre",
    "Other",
  ],
  "Guam": [
    "Dededo Village",
    "Hagåtña",
    "Mangilao Village",
    "Tamuning-Tumon-Harmon Village",
    "Yigo Village",
    "Other",
  ],
  "Guatemala": [
    "Antigua Guatemala",
    "Chimaltenango",
    "Chiquimula",
    "Cobán",
    "Cuilapa",
    "Escuintla",
    "Flores",
    "Guastatoya",
    "Guatemala City",
    "Huehuetenango",
    "Jalapa",
    "Jutiapa",
    "Mazatenango",
    "Puerto Barrios",
    "Quetzaltenango",
    "Retalhuleu",
    "Salamá",
    "San Marcos",
    "Santa Cruz del Quiché",
    "Sololá",
    "Totonicapán",
    "Zacapa",
    "Other",
  ],
  "Guernsey": [
    "Saint Peter Port",
    "Other",
  ],
  "Guinea": [
    "Boké",
    "Conakry",
    "Faranah",
    "Kankan",
    "Kindia",
    "Mamou",
    "Nzérékoré",
    "Other",
  ],
  "Guinea-Bissau": [
    "Bafatá",
    "Bissau",
    "Gabú",
    "Other",
  ],
  "Guyana": [
    "Georgetown",
    "Linden",
    "New Amsterdam",
    "Other",
  ],
  "Haiti": [
    "Cap-Haïtien",
    "Gonaïves",
    "Hinche",
    "Jacmel",
    "Jérémie",
    "Les Cayes",
    "Miragoâne",
    "Port-au-Prince",
    "Port-de-Paix",
    "Other",
  ],
  "Heard Island and McDonald Islands": [
    "Other",
    "Other",
  ],
  "Honduras": [
    "Ciudad Choluteca",
    "Comayagua",
    "Juticalpa",
    "La Ceiba",
    "La Paz",
    "San Pedro Sula",
    "Santa Bárbara",
    "Santa Rosa de Copán",
    "Tegucigalpa",
    "Yoro",
    "Other",
  ],
  "Hong Kong": [
    "Hong Kong",
    "Kwun Tong",
    "Mong Kok",
    "Sai Kung",
    "Sha Tin",
    "Sham Shui Po",
    "Tai Po",
    "Tsuen Wan",
    "Tuen Mun",
    "Wan Chai",
    "Wong Tai Sin",
    "Yuen Long",
    "Other",
  ],
  "Hungary": [
    "Békéscsaba",
    "Budapest",
    "Debrecen",
    "Eger",
    "Győr",
    "Kaposvár",
    "Kecskemét",
    "Miskolc",
    "Nyíregyháza",
    "Pécs",
    "Salgótarján",
    "Szeged",
    "Székesfehérvár",
    "Szekszárd",
    "Szolnok",
    "Szombathely",
    "Tatabánya",
    "Veszprém",
    "Zalaegerszeg",
    "Other",
  ],
  "Iceland": [
    "Akureyri",
    "Keflavík",
    "Reykjavík",
    "Other",
  ],
  "India": [
    "Agartala",
    "Aizawl",
    "Bengaluru",
    "Bhopal",
    "Bhubaneswar",
    "Chandigarh",
    "Chennai",
    "Daman",
    "Dehradun",
    "Delhi",
    "Gandhinagar",
    "Gangtok",
    "Hyderabad",
    "Imphal",
    "Itanagar",
    "Jaipur",
    "Jammu",
    "Kargil",
    "Kohima",
    "Kolkata",
    "Lucknow",
    "Mumbai",
    "New Delhi",
    "Panjim",
    "Patna",
    "Port Blair",
    "Puducherry",
    "Raipur",
    "Ranchi",
    "Shillong",
    "Shimla",
    "Srinagar",
    "Thiruvananthapuram",
    "Other",
  ],
  "Indonesia": [
    "Ambon",
    "Banda Aceh",
    "Bandar Lampung",
    "Bandung",
    "Bengkulu",
    "Denpasar",
    "Gorontalo",
    "Jakarta",
    "Jambi City",
    "Jayapura",
    "Kendari",
    "Kupang",
    "Makassar",
    "Manado",
    "Manokwari",
    "Mataram",
    "Medan",
    "Merauke",
    "Nabire",
    "Padang",
    "Palangkaraya",
    "Palembang",
    "Palu",
    "Pangkalpinang",
    "Pekanbaru",
    "Pontianak",
    "Samarinda",
    "Semarang",
    "Serang",
    "Sofifi",
    "Sorong",
    "Surabaya",
    "Tanjung Selor",
    "Wamena",
    "Yogyakarta",
    "Other",
  ],
  "Iran": [
    "Ahvaz",
    "Arāk",
    "Ardabīl",
    "Bandar Abbas",
    "Bīrjand",
    "Bojnūrd",
    "Bushehr",
    "Gorgān",
    "Hamadān",
    "Īlām",
    "Isfahan",
    "Karaj",
    "Kerman",
    "Kermanshah",
    "Khorramabad",
    "Mashhad",
    "Orūmīyeh",
    "Qazvin",
    "Qom",
    "Rasht",
    "Sanandaj",
    "Sari",
    "Semnan",
    "Shahr-e Kord",
    "Shiraz",
    "Tabriz",
    "Tehran",
    "Yasuj",
    "Yazd",
    "Zahedan",
    "Zanjan",
    "Other",
  ],
  "Iraq": [
    "Al ‘Amārah",
    "Al Diwaniyah",
    "Al Hillah",
    "Al-Kut",
    "As Samawah",
    "Baghdad",
    "Baqubah",
    "Basrah",
    "Dihok",
    "Erbil",
    "Karbala",
    "Kirkuk",
    "Mosul",
    "Najaf",
    "Nasiriyah",
    "Ramadi",
    "Sulaymaniyah",
    "Tikrīt",
    "Other",
  ],
  "Ireland": [
    "Dublin",
    "Galway",
    "Swords",
    "Other",
  ],
  "Isle of Man": [
    "Douglas",
    "Other",
  ],
  "Israel": [
    "Ariel",
    "Beersheba",
    "Haifa",
    "Jerusalem",
    "Nazareth",
    "Ramla",
    "Tel Aviv",
    "Other",
  ],
  "Italy": [
    "Ancona",
    "Aosta",
    "Bari",
    "Bologna",
    "Cagliari",
    "Campobasso",
    "Catanzaro",
    "Florence",
    "Genoa",
    "L'Aquila",
    "Milan",
    "Naples",
    "Palermo",
    "Perugia",
    "Potenza",
    "Rome",
    "Trento",
    "Trieste",
    "Turin",
    "Venice",
    "Other",
  ],
  "Ivory Coast": [
    "Abengourou",
    "Abidjan",
    "Bondoukou",
    "Bouaké",
    "Daloa",
    "Dimbokro",
    "Gagnoa",
    "Korhogo",
    "Man",
    "Odienné",
    "San-Pédro",
    "Séguéla",
    "Yamoussoukro",
    "Other",
  ],
  "Jamaica": [
    "Half Way Tree",
    "Kingston",
    "Mandeville",
    "May Pen",
    "Montego Bay",
    "Savanna-la-Mar",
    "Spanish Town",
    "Other",
  ],
  "Japan": [
    "Akita",
    "Aomori",
    "Chiba",
    "Fukui-shi",
    "Fukuoka",
    "Fukushima",
    "Gifu",
    "Hiroshima",
    "Kagoshima",
    "Kanazawa",
    "Kobe",
    "Kochi",
    "Kofu",
    "Kumamoto",
    "Kyoto",
    "Maebashi",
    "Matsue",
    "Matsuyama",
    "Mito",
    "Miyazaki",
    "Morioka",
    "Nagano",
    "Nagasaki",
    "Nagoya",
    "Naha",
    "Nara-shi",
    "Niigata",
    "Ōita",
    "Okayama",
    "Osaka",
    "Ōtsu",
    "Saga",
    "Saitama",
    "Sapporo",
    "Sendai",
    "Shizuoka",
    "Takamatsu",
    "Tokushima",
    "Tokyo",
    "Tottori-shi",
    "Toyama",
    "Tsu",
    "Utsunomiya",
    "Wakayama",
    "Yamagata",
    "Yamaguchi",
    "Yokohama",
    "Other",
  ],
  "Jersey": [
    "Saint Helier",
    "Other",
  ],
  "Jordan": [
    "‘Ajlūn",
    "Amman",
    "Aqaba",
    "As Salţ",
    "Aţ Ţafīlah",
    "Irbid",
    "Jarash",
    "Karak City",
    "Ma'an",
    "Mādabā",
    "Mafraq",
    "Zarqa",
    "Other",
  ],
  "Kazakhstan": [
    "Aktau",
    "Aktobe",
    "Almaty",
    "Astana",
    "Atyrau",
    "Baikonur",
    "Karagandy",
    "Kokshetau",
    "Konayev",
    "Kostanay",
    "Kyzylorda",
    "Oral",
    "Pavlodar",
    "Petropavl",
    "Semey",
    "Shymkent",
    "Taldykorgan",
    "Taraz",
    "Turkestan",
    "Ust-Kamenogorsk",
    "Zhezqazghan",
    "Other",
  ],
  "Kenya": [
    "Bungoma",
    "Busia",
    "Eldoret",
    "Embu",
    "Garissa",
    "Hola",
    "Homa Bay",
    "Isiolo",
    "Iten",
    "Kabarnet",
    "Kajiado",
    "Kakamega",
    "Kapenguria",
    "Kapsabet",
    "Kericho",
    "Kerugoya",
    "Kiambu",
    "Kilifi",
    "Kisii",
    "Kisumu",
    "Kitale",
    "Kitui",
    "Lamu",
    "Lodwar",
    "Machakos",
    "Mandera",
    "Maralal",
    "Marsabit",
    "Mbale",
    "Meru",
    "Migori",
    "Mombasa",
    "Murang’a",
    "Nairobi",
    "Nakuru",
    "Narok",
    "Nyamira",
    "Nyeri",
    "Ol Kalou",
    "Siaya",
    "Wajir",
    "Wote",
    "Other",
  ],
  "Kiribati": [
    "Tarawa",
    "Other",
  ],
  "Kosovo": [
    "Ferizaj",
    "Gjakovë",
    "Gjilan",
    "Mitrovicë",
    "Pejë",
    "Pristina",
    "Prizren",
    "Other",
  ],
  "Kuwait": [
    "Al Aḩmadī",
    "Al Farwānīyah",
    "Al Jahrā’",
    "Ḩawallī",
    "Kuwait City",
    "Other",
  ],
  "Kyrgyzstan": [
    "Batken",
    "Bishkek",
    "Jalal-Abad",
    "Karakol",
    "Naryn",
    "Osh",
    "Talas",
    "Other",
  ],
  "Laos": [
    "Luang Prabang",
    "Muang Phônsavan",
    "Muang Xay",
    "Pakse",
    "Pakxan",
    "Savannakhet",
    "Sekong",
    "Thakhèk",
    "Vientiane",
    "Xam Nua",
    "Other",
  ],
  "Latvia": [
    "Cēsis",
    "Daugavpils",
    "Jēkabpils",
    "Jelgava",
    "Jūrmala",
    "Liepāja",
    "Mārupe",
    "Ogre",
    "Rēzekne",
    "Riga",
    "Salaspils",
    "Tukums",
    "Valmiera",
    "Ventspils",
    "Other",
  ],
  "Lebanon": [
    "Baalbek",
    "Beirut",
    "Nabatîyé et Tahta",
    "Sidon",
    "Tripoli",
    "Zahlé",
    "Other",
  ],
  "Lesotho": [
    "Butha-Buthe",
    "Hlotse",
    "Mafeteng",
    "Maseru",
    "Mohale's Hoek",
    "Quthing",
    "Teyateyaneng",
    "Thaba-Tseka",
    "Other",
  ],
  "Liberia": [
    "Buchanan",
    "Gbarnga",
    "Greenville",
    "Harper",
    "Kakata",
    "Monrovia",
    "Sanniquellie",
    "Tubmanburg",
    "Voinjama",
    "Zwedru",
    "Other",
  ],
  "Libya": [
    "Ajdabiya",
    "Al ‘Azīzīyah",
    "Al Bayḑā’",
    "Al Khums",
    "Al Marj",
    "Az Zāwīyah",
    "Benghazi",
    "Darnah",
    "Gharyan",
    "Hūn",
    "Misratah",
    "Murzuk",
    "Nālūt",
    "Sabha",
    "Sirte",
    "Tobruk",
    "Tripoli",
    "Ubari",
    "Zuwarah",
    "Other",
  ],
  "Liechtenstein": [
    "Vaduz",
    "Other",
  ],
  "Lithuania": [
    "Alytus",
    "Kaunas",
    "Klaipėda",
    "Marijampolė",
    "Panevėžys",
    "Šiauliai",
    "Taurage",
    "Telsiai",
    "Utena",
    "Vilnius",
    "Other",
  ],
  "Luxembourg": [
    "Luxembourg",
    "Other",
  ],
  "Macao": [
    "Macau",
    "Other",
  ],
  "Madagascar": [
    "Ambatondrazaka",
    "Ambositra",
    "Ambovombe",
    "Antananarivo",
    "Antsirabe",
    "Antsiranana",
    "Antsohihy",
    "Farafangana",
    "Fenoarivo Atsinanana",
    "Fianarantsoa",
    "Ihosy",
    "Maevatanana",
    "Mahajanga",
    "Maintirano",
    "Manakara",
    "Morondava",
    "Sambava",
    "Toamasina",
    "Tôlanaro",
    "Toliara",
    "Tsiroanomandidy",
    "Other",
  ],
  "Malawi": [
    "Blantyre",
    "Lilongwe",
    "Mzuzu",
    "Other",
  ],
  "Malaysia": [
    "Alor Setar",
    "George Town",
    "Ipoh",
    "Johor Bahru",
    "Kangar",
    "Kota Bharu",
    "Kota Kinabalu",
    "Kuala Lumpur",
    "Kuala Terengganu",
    "Kuantan",
    "Kuching",
    "Labuan",
    "Malacca",
    "Seremban",
    "Other",
  ],
  "Maldives": [
    "Male",
    "Other",
  ],
  "Mali": [
    "Bamako",
    "Gao",
    "Kayes",
    "Kidal",
    "Koulikoro",
    "Mopti",
    "Ségou",
    "Sikasso",
    "Timbuktu",
    "Other",
  ],
  "Malta": [
    "Birkirkara",
    "Mosta",
    "Qormi",
    "San Pawl il-Baħar",
    "Sliema",
    "Valletta",
    "Żabbar",
    "Other",
  ],
  "Marshall Islands": [
    "Majuro",
    "Other",
  ],
  "Martinique": [
    "Fort-de-France",
    "Other",
  ],
  "Mauritania": [
    "Akjoujt",
    "Aleg",
    "Atar",
    "Ayoun El Atrous",
    "Dar Naim",
    "Kaédi",
    "Kiffa",
    "Néma",
    "Nouadhibou",
    "Nouakchott",
    "Rosso",
    "Sélibaby",
    "Tevragh Zeina",
    "Zouérat",
    "Other",
  ],
  "Mauritius": [
    "Beau Bassin-Rose Hill",
    "Centre de Flacq",
    "Port Louis",
    "Other",
  ],
  "Mayotte": [
    "Dzaoudzi",
    "Koungou",
    "Mamoudzou",
    "Other",
  ],
  "Mexico": [
    "Aguascalientes",
    "Campeche",
    "Chetumal",
    "Chihuahua",
    "Chilpancingo",
    "Ciudad Victoria",
    "Colima",
    "Cuernavaca",
    "Culiacán",
    "Guadalajara",
    "Guanajuato",
    "Hermosillo",
    "La Paz",
    "Mérida",
    "Mexicali",
    "Mexico City",
    "Monterrey",
    "Morelia",
    "Oaxaca",
    "Pachuca de Soto",
    "Puebla",
    "Saltillo",
    "San Luis Potosí",
    "Santiago de Querétaro",
    "Tepic",
    "Tlaxcala",
    "Toluca",
    "Tuxtla",
    "Villahermosa",
    "Xalapa de Enríquez",
    "Zacatecas",
    "Other",
  ],
  "Micronesia": [
    "Palikir",
    "Other",
  ],
  "Moldova": [
    "Bălţi",
    "Bender",
    "Cahul",
    "Căuşeni",
    "Chisinau",
    "Comrat",
    "Drochia",
    "Edineţ",
    "Floreşti",
    "Hînceşti",
    "Orhei",
    "Soroca",
    "Strășeni",
    "Tiraspol",
    "Ungheni",
    "Other",
  ],
  "Monaco": [
    "Monaco",
    "Other",
  ],
  "Mongolia": [
    "Altai",
    "Arvayheer",
    "Baruun-Urt",
    "Bayanhongor",
    "Bulgan",
    "Choibalsan",
    "Dalandzadgad",
    "Darhan",
    "Dzuunmod",
    "Erdenet",
    "Khovd",
    "Mörön",
    "Ölgii",
    "Saynshand",
    "Sühbaatar",
    "Tsetserleg",
    "Ulaangom",
    "Ulan Bator",
    "Uliastay",
    "Undurkhaan",
    "Other",
  ],
  "Montenegro": [
    "Bar",
    "Bijelo Polje",
    "Budva",
    "Cetinje",
    "Herceg Novi",
    "Nikšić",
    "Pljevlja",
    "Podgorica",
    "Other",
  ],
  "Montserrat": [
    "Plymouth",
    "Other",
  ],
  "Morocco": [
    "Agadir",
    "Beni Mellal",
    "Casablanca",
    "Fes",
    "Guelmim",
    "Kenitra",
    "Marrakesh",
    "Oujda",
    "Rabat",
    "Tangier",
    "Other",
  ],
  "Mozambique": [
    "Beira",
    "Chimoio",
    "Inhambane",
    "Lichinga",
    "Maputo",
    "Matola",
    "Nampula",
    "Pemba",
    "Quelimane",
    "Tete",
    "Xai-Xai",
    "Other",
  ],
  "Myanmar": [
    "Bago",
    "Dawei",
    "Hakha",
    "Hpa-An",
    "Loikaw",
    "Magway",
    "Mandalay",
    "Mawlamyine",
    "Monywa",
    "Myitkyina",
    "Nay Pyi Taw",
    "Pathein",
    "Sittwe",
    "Taunggyi",
    "Yangon",
    "Other",
  ],
  "Namibia": [
    "Gobabis",
    "Katima Mulilo",
    "Keetmanshoop",
    "Oshakati",
    "Otjiwarongo",
    "Rundu",
    "Swakopmund",
    "Windhoek",
    "Other",
  ],
  "Nauru": [
    "Yaren",
    "Other",
  ],
  "Nepal": [
    "Birendranagar",
    "Butwāl",
    "Dhankutā",
    "Dipayal",
    "Janakpur",
    "Kathmandu",
    "Pokhara",
    "Other",
  ],
  "Netherlands Antilles": [
    "Other",
    "Other",
  ],
  "New Caledonia": [
    "Nouméa",
    "Other",
  ],
  "New Zealand": [
    "Auckland",
    "Blenheim",
    "Christchurch",
    "Dunedin",
    "Gisborne",
    "Hamilton",
    "Invercargill",
    "Napier",
    "Nelson",
    "New Plymouth",
    "Palmerston North",
    "Richmond",
    "Wellington",
    "Whakatane",
    "Whangarei",
    "Other",
  ],
  "Nicaragua": [
    "Bluefields",
    "Boaco",
    "Chinandega",
    "Estelí",
    "Granada",
    "Jinotega",
    "Jinotepe",
    "Juigalpa",
    "León",
    "Managua",
    "Masaya",
    "Matagalpa",
    "Ocotal",
    "Puerto Cabezas",
    "Rivas",
    "Somoto",
    "Other",
  ],
  "Niger": [
    "Agadez",
    "Diffa",
    "Dosso",
    "Maradi",
    "Niamey",
    "Tahoua",
    "Tillabéri",
    "Zinder",
    "Other",
  ],
  "Nigeria": [
    "Abakaliki",
    "Abeokuta",
    "Abuja",
    "Ado-Ekiti",
    "Akure",
    "Asaba",
    "Awka",
    "Bauchi",
    "Benin City",
    "Birnin Kebbi",
    "Calabar",
    "Damaturu",
    "Dutse",
    "Enugu",
    "Gombe",
    "Gusau",
    "Ibadan",
    "Ikeja",
    "Ilorin",
    "Jalingo",
    "Jos",
    "Kaduna",
    "Kano",
    "Katsina",
    "Lafia",
    "Lokoja",
    "Maiduguri",
    "Makurdi",
    "Minna",
    "Osogbo",
    "Owerri",
    "Port Harcourt",
    "Sokoto",
    "Umuahia",
    "Uyo",
    "Yenagoa",
    "Yola",
    "Other",
  ],
  "Niue": [
    "Alofi",
    "Other",
  ],
  "Norfolk Island": [
    "Kingston",
    "Other",
  ],
  "North Korea": [
    "Chongjin",
    "Haeju",
    "Hamhŭng",
    "Hyesan",
    "Kaesŏng",
    "Kanggye",
    "Namp’o",
    "P’yŏngsŏng",
    "Pyongyang",
    "Rajin",
    "Sariwŏn-si",
    "Sinŭiju",
    "Wŏnsan",
    "Other",
  ],
  "North Macedonia": [
    "Bitola",
    "Bogovinje",
    "Brvenica",
    "Centar Župa",
    "Debar",
    "Delcevo",
    "Gevgelija",
    "Gostivar",
    "Ilinden",
    "Kavadarci",
    "Kičevo",
    "Kochani",
    "Kriva Palanka",
    "Kumanovo",
    "Lipkovo",
    "Negotino",
    "Ohrid",
    "Prilep",
    "Radovis",
    "Resen",
    "Shtip",
    "Skopje",
    "Struga",
    "Strumica",
    "Studeničani",
    "Tearce",
    "Tetovo",
    "Veles",
    "Vinica",
    "Zelino",
    "Other",
  ],
  "Northern Mariana Islands": [
    "Saipan",
    "Other",
  ],
  "Norway": [
    "Arendal",
    "Bergen",
    "Bodø",
    "Drammen",
    "Hamar",
    "Kristiansand",
    "Lillehammer",
    "Molde",
    "Oslo",
    "Sarpsborg",
    "Skien",
    "Stavanger",
    "Tønsberg",
    "Tromsø",
    "Other",
  ],
  "Oman": [
    "Al Buraymī",
    "Ibrā’",
    "Khasab",
    "Muscat",
    "Nizwá",
    "Şalālah",
    "Sohar",
    "Sur",
    "Other",
  ],
  "Other": [
    "Other",
    "Other",
  ],
  "Pakistan": [
    "Gilgit",
    "Islamabad",
    "Karachi",
    "Lahore",
    "Muzaffarābād",
    "Peshawar",
    "Quetta",
    "Other",
  ],
  "Palau": [
    "Ngerulmud",
    "Other",
  ],
  "Palestinian Territory": [
    "Gaza",
    "Jericho",
    "Other",
  ],
  "Panama": [
    "Colón",
    "David",
    "La Chorrera",
    "Panamá",
    "Penonomé",
    "Santiago de Veraguas",
    "Other",
  ],
  "Papua New Guinea": [
    "Daru",
    "Goroka",
    "Kimbe",
    "Kokopo",
    "Lae",
    "Madang",
    "Mendi",
    "Mount Hagen",
    "Popondetta",
    "Port Moresby",
    "Wewak",
    "Other",
  ],
  "Paraguay": [
    "Asunción",
    "Caacupé",
    "Caazapá",
    "Ciudad del Este",
    "Concepción",
    "Coronel Oviedo",
    "Encarnación",
    "Filadelfia",
    "Pedro Juan Caballero",
    "Pilar",
    "San Juan Bautista",
    "Villa Hayes",
    "Villarrica",
    "Other",
  ],
  "Peru": [
    "Abancay",
    "Arequipa",
    "Ayacucho",
    "Cajamarca",
    "Callao",
    "Cerro de Pasco",
    "Chachapoyas",
    "Chiclayo",
    "Cusco",
    "Huacho",
    "Huancavelica",
    "Huancayo",
    "Huánuco",
    "Huaraz",
    "Ica",
    "Iquitos",
    "Lima",
    "Moquegua",
    "Moyobamba",
    "Piura",
    "Pucallpa",
    "Puerto Maldonado",
    "Puno",
    "Tacna",
    "Trujillo",
    "Tumbes",
    "Other",
  ],
  "Philippines": [
    "Baguio",
    "Butuan",
    "Calamba",
    "Calapan",
    "Cebu City",
    "Cotabato",
    "Davao",
    "Koronadal",
    "Manila",
    "Pagadian",
    "San Fernando",
    "Tuguegarao",
    "Other",
  ],
  "Pitcairn": [
    "Adamstown",
    "Other",
  ],
  "Poland": [
    "Białystok",
    "Bydgoszcz",
    "Gdańsk",
    "Gorzów Wielkopolski",
    "Katowice",
    "Kielce",
    "Kraków",
    "Łódź",
    "Lublin",
    "Olsztyn",
    "Opole",
    "Poznań",
    "Rzeszów",
    "Szczecin",
    "Warsaw",
    "Wrocław",
    "Zielona Góra",
    "Other",
  ],
  "Portugal": [
    "Aveiro",
    "Beja",
    "Braga",
    "Bragança",
    "Castelo Branco",
    "Coimbra",
    "Évora",
    "Faro",
    "Funchal",
    "Guarda",
    "Leiria",
    "Lisbon",
    "Ponta Delgada",
    "Portalegre",
    "Porto",
    "Santarém",
    "Setúbal",
    "Viana do Castelo",
    "Vila Real",
    "Viseu",
    "Other",
  ],
  "Puerto Rico": [
    "Aguadilla",
    "Arecibo",
    "Barceloneta",
    "Bayamón",
    "Caguas",
    "Carolina",
    "Cataño",
    "Cayey",
    "Fajardo",
    "Guayama",
    "Guaynabo",
    "Humacao",
    "Manatí",
    "Mayagüez",
    "Ponce",
    "San Juan",
    "Trujillo Alto",
    "Vega Baja",
    "Yauco",
    "Other",
  ],
  "Qatar": [
    "Al Khawr",
    "Al Wakrah",
    "Ar Rayyān",
    "Az̧ Z̧a‘āyin",
    "Doha",
    "Other",
  ],
  "Republic of the Congo": [
    "Brazzaville",
    "Djambala",
    "Dolisie",
    "Impfondo",
    "Ouesso",
    "Owando",
    "Pointe-Noire",
    "Sibiti",
    "Other",
  ],
  "Reunion": [
    "Saint-Denis",
    "Other",
  ],
  "Romania": [
    "Alba Iulia",
    "Alexandria",
    "Arad",
    "Bacău",
    "Baia Mare",
    "Bistriţa",
    "Botoşani",
    "Brăila",
    "Braşov",
    "Bucharest",
    "Buzău",
    "Cluj-Napoca",
    "Constanţa",
    "Craiova",
    "Drobeta-Turnu Severin",
    "Focșani",
    "Galaţi",
    "Giurgiu",
    "Iaşi",
    "Miercurea-Ciuc",
    "Oradea",
    "Piatra Neamţ",
    "Piteşti",
    "Ploieşti",
    "Râmnicu Vâlcea",
    "Reşiţa",
    "Satu Mare",
    "Sfântu Gheorghe",
    "Sibiu",
    "Slatina",
    "Slobozia",
    "Suceava",
    "Târgovişte",
    "Târgu Jiu",
    "Târgu Mureş",
    "Timişoara",
    "Tulcea",
    "Vaslui",
    "Zalău",
    "Other",
  ],
  "Russia": [
    "Abakan",
    "Anadyr",
    "Arkhangel’sk",
    "Astrakhan",
    "Barnaul",
    "Belgorod",
    "Birobidzhan",
    "Blagoveshchensk",
    "Bryansk",
    "Cheboksary",
    "Chelyabinsk",
    "Cherkessk",
    "Chita",
    "Elista",
    "Gorno-Altaysk",
    "Grozny",
    "Irkutsk",
    "Ivanovo",
    "Izhevsk",
    "Kaliningrad",
    "Kaluga",
    "Kazan",
    "Kemerovo",
    "Khabarovsk",
    "Khanty-Mansiysk",
    "Kirov",
    "Kostroma",
    "Krasnodar",
    "Krasnoyarsk",
    "Kurgan",
    "Kursk",
    "Kyzyl",
    "Lipetsk",
    "Magadan",
    "Makhachkala",
    "Maykop",
    "Moscow",
    "Murmansk",
    "Nalchik",
    "Nar'yan-Mar",
    "Nizhniy Novgorod",
    "Novosibirsk",
    "Omsk",
    "Orël",
    "Orenburg",
    "Penza",
    "Perm",
    "Petropavlovsk-Kamchatsky",
    "Petrozavodsk",
    "Pskov",
    "Rostov-na-Donu",
    "Ryazan’",
    "Saint Petersburg",
    "Salekhard",
    "Samara",
    "Saransk",
    "Saratov",
    "Smolensk",
    "Stavropol’",
    "Syktyvkar",
    "Tambov",
    "Tomsk",
    "Tula",
    "Tver",
    "Tyumen",
    "Ufa",
    "Ulan-Ude",
    "Ulyanovsk",
    "Velikiy Novgorod",
    "Vladikavkaz",
    "Vladimir",
    "Vladivostok",
    "Volgograd",
    "Vologda",
    "Voronezh",
    "Yakutsk",
    "Yaroslavl",
    "Yekaterinburg",
    "Yoshkar-Ola",
    "Yuzhno-Sakhalinsk",
    "Other",
  ],
  "Rwanda": [
    "Byumba",
    "Kibuye",
    "Kigali",
    "Nyanza",
    "Rwamagana",
    "Other",
  ],
  "Saint Barthelemy": [
    "Gustavia",
    "Other",
  ],
  "Saint Helena": [
    "Jamestown",
    "Other",
  ],
  "Saint Kitts and Nevis": [
    "Basseterre",
    "Other",
  ],
  "Saint Lucia": [
    "Castries",
    "Gros Islet",
    "Other",
  ],
  "Saint Martin": [
    "Marigot",
    "Other",
  ],
  "Saint Pierre and Miquelon": [
    "Saint-Pierre",
    "Other",
  ],
  "Saint Vincent and the Grenadines": [
    "Kingstown",
    "Other",
  ],
  "Samoa": [
    "Apia",
    "Other",
  ],
  "San Marino": [
    "San Marino",
    "Other",
  ],
  "Sao Tome and Principe": [
    "São Tomé",
    "Other",
  ],
  "Saudi Arabia": [
    "Abha",
    "Al Bahah",
    "Arar",
    "Buraydah",
    "Dammam",
    "Ha'il",
    "Jizan",
    "Madinah",
    "Makkah",
    "Najrān",
    "Riyadh",
    "Sakakah",
    "Tabuk",
    "Other",
  ],
  "Senegal": [
    "Dakar",
    "Diourbel",
    "Fatick",
    "Kaffrine",
    "Kaolack",
    "Kédougou",
    "Kolda",
    "Louga",
    "Matam",
    "Saint-Louis",
    "Sédhiou",
    "Tambacounda",
    "Ziguinchor",
    "Other",
  ],
  "Serbia": [
    "Belgrade",
    "Novi Sad",
    "Other",
  ],
  "Serbia and Montenegro": [
    "Other",
    "Other",
  ],
  "Seychelles": [
    "Victoria",
    "Other",
  ],
  "Sierra Leone": [
    "Bo",
    "Freetown",
    "Kenema",
    "Makeni",
    "Port Loko",
    "Other",
  ],
  "Singapore": [
    "Singapore",
    "Other",
  ],
  "Sint Maarten": [
    "Philipsburg",
    "Other",
  ],
  "Slovakia": [
    "Banská Bystrica",
    "Bratislava",
    "Košice",
    "Nitra",
    "Prešov",
    "Trenčín",
    "Trnava",
    "Žilina",
    "Other",
  ],
  "Slovenia": [
    "Celje",
    "Koper",
    "Kranj",
    "Ljubljana",
    "Maribor",
    "Novo Mesto",
    "Ptuj",
    "Trbovlje",
    "Velenje",
    "Other",
  ],
  "Solomon Islands": [
    "Honiara",
    "Other",
  ],
  "Somalia": [
    "Baidoa",
    "Beledweyne",
    "Bosaso",
    "Burao",
    "Ceerigaabo",
    "Gaalkacyo",
    "Garoowe",
    "Hargeysa",
    "Jawhar",
    "Kismayo",
    "Laascaanood",
    "Marka",
    "Mogadishu",
    "Other",
  ],
  "South Africa": [
    "Bhisho",
    "Bloemfontein",
    "Cape Town",
    "Johannesburg",
    "Kimberley",
    "Mafikeng",
    "Mbombela",
    "Pietermaritzburg",
    "Polokwane",
    "Pretoria",
    "Other",
  ],
  "South Georgia and the South Sandwich Islands": [
    "Grytviken",
    "Other",
  ],
  "South Korea": [
    "Andong",
    "Busan",
    "Changwon",
    "Cheongju-si",
    "Chuncheon",
    "Daegu",
    "Daejeon",
    "Gwangju",
    "Hongseong",
    "Incheon",
    "Jeju City",
    "Jeonju",
    "Muan",
    "Sejong",
    "Seoul",
    "Suwon",
    "Ulsan",
    "Other",
  ],
  "South Sudan": [
    "Aweil",
    "Bor",
    "Juba",
    "Kuacjok",
    "Malakal",
    "Rumbek",
    "Torit",
    "Wau",
    "Yambio",
    "Other",
  ],
  "Spain": [
    "Barcelona",
    "Ceuta",
    "Gasteiz / Vitoria",
    "Las Palmas de Gran Canaria",
    "Logroño",
    "Madrid",
    "Melilla",
    "Mérida",
    "Murcia",
    "Oviedo",
    "Palma",
    "Pamplona",
    "Santa Cruz de Tenerife",
    "Santander",
    "Santiago de Compostela",
    "Sevilla",
    "Toledo",
    "Valencia",
    "Valladolid",
    "Zaragoza",
    "Other",
  ],
  "Sri Lanka": [
    "Anuradhapura",
    "Badulla",
    "Colombo",
    "Galle",
    "Jaffna",
    "Kandy",
    "Kurunegala",
    "Ratnapura",
    "Trincomalee",
    "Other",
  ],
  "Sudan": [
    "Ad-Damazin",
    "Ad-Damir",
    "Al Qadarif",
    "Al-Junaynah",
    "Dongola",
    "El Daein",
    "El Fasher",
    "El Obeid",
    "Kadugli",
    "Kassala",
    "Khartoum",
    "Nyala",
    "Port Sudan",
    "Rabak",
    "Singa",
    "Wad Medani",
    "Zalinjay",
    "Other",
  ],
  "Suriname": [
    "Lelydorp",
    "Paramaribo",
    "Other",
  ],
  "Svalbard and Jan Mayen": [
    "Longyearbyen",
    "Other",
  ],
  "Sweden": [
    "Falun",
    "Gävle",
    "Göteborg",
    "Halmstad",
    "Härnösand",
    "Jönköping",
    "Kalmar",
    "Karlskrona",
    "Karlstad",
    "Linköping",
    "Luleå",
    "Malmö",
    "Nyköping",
    "Örebro",
    "Östersund",
    "Stockholm",
    "Umeå",
    "Uppsala",
    "Västerås",
    "Växjö",
    "Visby",
    "Other",
  ],
  "Switzerland": [
    "Aarau",
    "Basel",
    "Bellinzona",
    "Bern",
    "Chur",
    "Frauenfeld",
    "Fribourg",
    "Genève",
    "Herisau",
    "Lausanne",
    "Luzern",
    "Neuchâtel",
    "Sankt Gallen",
    "Schaffhausen",
    "Schwyz",
    "Sitten",
    "Solothurn",
    "Zug",
    "Zürich",
    "Other",
  ],
  "Syria": [
    "Al Ḩasakah",
    "Al Qunayţirah",
    "Aleppo",
    "Ar Raqqah",
    "As-Suwayda",
    "Damascus",
    "Dar‘ā",
    "Deir ez-Zor",
    "Ḩamāh",
    "Homs",
    "Idlib",
    "Latakia",
    "Ţarţūs",
    "Other",
  ],
  "Taiwan": [
    "Jincheng",
    "Kaohsiung",
    "Taipei",
    "Zhongxing New Village",
    "Other",
  ],
  "Tajikistan": [
    "Bokhtar",
    "Dushanbe",
    "Khorugh",
    "Khujand",
    "Other",
  ],
  "Tanzania": [
    "Arusha",
    "Babati",
    "Bukoba",
    "Chake Chake",
    "Dar es Salaam",
    "Dodoma",
    "Geita",
    "Iringa",
    "Kibaha",
    "Kigoma",
    "Lindi",
    "Mbeya",
    "Morogoro",
    "Moshi",
    "Mpanda",
    "Mtwara",
    "Musoma",
    "Mwanza",
    "Njombe",
    "Shinyanga",
    "Singida",
    "Songea",
    "Sumbawanga",
    "Tabora",
    "Tanga",
    "Vwawa",
    "Wete",
    "Zanzibar",
    "Other",
  ],
  "Thailand": [
    "Amnat Charoen",
    "Bangkok",
    "Buri Ram",
    "Chachoengsao",
    "Chai Nat",
    "Chaiyaphum",
    "Chanthaburi",
    "Chiang Mai",
    "Chiang Rai",
    "Chon Buri",
    "Chumphon",
    "Kalasin",
    "Kamphaeng Phet",
    "Kanchanaburi",
    "Khon Kaen",
    "Krabi",
    "Lampang",
    "Lamphun",
    "Loei",
    "Lop Buri",
    "Maha Sarakham",
    "Mueang Nonthaburi",
    "Mukdahan",
    "Nakhon Nayok",
    "Nakhon Pathom",
    "Nakhon Phanom",
    "Nakhon Ratchasima",
    "Nakhon Sawan",
    "Nakhon Si Thammarat",
    "Nan",
    "Narathiwat",
    "Nong Bua Lamphu",
    "Nong Khai",
    "Pathum Thani",
    "Pattani",
    "Phatthalung",
    "Phayao",
    "Phetchabun",
    "Phetchaburi",
    "Phichit",
    "Phitsanulok",
    "Phra Nakhon Si Ayutthaya",
    "Phrae",
    "Phuket",
    "Prachin Buri",
    "Prachuap Khiri Khan",
    "Ranong",
    "Ratchaburi",
    "Rayong",
    "Roi Et",
    "Sa Kaeo",
    "Sakon Nakhon",
    "Samut Prakan",
    "Samut Sakhon",
    "Samut Songkhram",
    "Saraburi",
    "Satun",
    "Si Sa Ket",
    "Sing Buri",
    "Songkhla",
    "Sukhothai",
    "Suphan Buri",
    "Surat Thani",
    "Surin",
    "Tak",
    "Trang",
    "Trat",
    "Ubon Ratchathani",
    "Udon Thani",
    "Uthai Thani",
    "Uttaradit",
    "Yala",
    "Yasothon",
    "Other",
  ],
  "The Netherlands": [
    "'s-Hertogenbosch",
    "Amsterdam",
    "Arnhem",
    "Assen",
    "Groningen",
    "Haarlem",
    "Leeuwarden",
    "Lelystad",
    "Maastricht",
    "Middelburg",
    "Utrecht",
    "Zwolle",
    "Other",
  ],
  "Timor Leste": [
    "Aileu",
    "Baukau",
    "Dili",
    "Likisá",
    "Lospalos",
    "Maliana",
    "Suai",
    "Other",
  ],
  "Togo": [
    "Atakpamé",
    "Dapaong",
    "Kara",
    "Lomé",
    "Sokodé",
    "Tsévié",
    "Other",
  ],
  "Tokelau": [
    "Other",
    "Other",
  ],
  "Tonga": [
    "Nuku‘alofa",
    "Other",
  ],
  "Trinidad and Tobago": [
    "Arima",
    "Chaguanas",
    "Diego Martin",
    "Laventille",
    "Point Fortin",
    "Port of Spain",
    "Rio Claro",
    "San Fernando",
    "Sangre Grande",
    "Scarborough",
    "Tunapuna",
    "Other",
  ],
  "Tunisia": [
    "Aryanah",
    "Béja",
    "Ben Arous",
    "Bizerte",
    "El Kef",
    "Gabès",
    "Gafsa",
    "Jendouba",
    "Kairouan",
    "Kasserine",
    "Kebili",
    "Mahdia",
    "Manouba",
    "Medenine",
    "Monastir",
    "Nabeul",
    "Sfax",
    "Sidi Bouzid",
    "Siliana",
    "Sousse",
    "Tataouine",
    "Tozeur",
    "Tunis",
    "Zaghouan",
    "Other",
  ],
  "Turkey": [
    "Adana",
    "Adapazarı",
    "Adıyaman",
    "Afyonkarahisar",
    "Ağrı",
    "Aksaray",
    "Amasya",
    "Ankara",
    "Antakya",
    "Antalya",
    "Ardahan",
    "Artvin",
    "Aydın",
    "Balıkesir",
    "Bartın",
    "Batman",
    "Bayburt",
    "Bilecik",
    "Bingöl",
    "Bitlis",
    "Bolu",
    "Burdur",
    "Bursa",
    "Çanakkale",
    "Çankırı",
    "Çorum",
    "Denizli",
    "Diyarbakır",
    "Düzce",
    "Edirne",
    "Elazığ",
    "Erzincan",
    "Erzurum",
    "Eskişehir",
    "Gaziantep",
    "Giresun",
    "Gümüşhane",
    "Hakkâri",
    "Iğdır",
    "Isparta",
    "Istanbul",
    "İzmir",
    "İzmit",
    "Kahramanmaraş",
    "Karabük",
    "Karaman",
    "Kars",
    "Kastamonu",
    "Kayseri",
    "Kilis",
    "Kırıkkale",
    "Kırklareli",
    "Kırşehir",
    "Konya",
    "Kütahya",
    "Malatya",
    "Manisa",
    "Mardin",
    "Mersin",
    "Muğla",
    "Muş",
    "Nevşehir",
    "Niğde",
    "Ordu",
    "Osmaniye",
    "Rize",
    "Samsun",
    "Şanlıurfa",
    "Siirt",
    "Sinop",
    "Sivas",
    "Şırnak",
    "Tekirdağ",
    "Tokat",
    "Trabzon",
    "Tunceli",
    "Uşak",
    "Van",
    "Yalova",
    "Yozgat",
    "Zonguldak",
    "Other",
  ],
  "Turkmenistan": [
    "Änew",
    "Ashgabat",
    "Balkanabat",
    "Daşoguz",
    "Mary",
    "Türkmenabat",
    "Other",
  ],
  "Turks and Caicos Islands": [
    "Cockburn Town",
    "Other",
  ],
  "Tuvalu": [
    "Funafuti",
    "Other",
  ],
  "U.S. Virgin Islands": [
    "Charlotte Amalie",
    "Saint Croix",
    "Other",
  ],
  "Uganda": [
    "Gulu",
    "Jinja",
    "Kampala",
    "Mbarara",
    "Other",
  ],
  "Ukraine": [
    "Cherkasy",
    "Chernihiv",
    "Chernivtsi",
    "Dnipro",
    "Donetsk",
    "Ivano-Frankivsk",
    "Kharkiv",
    "Kherson",
    "Khmelnytskyi",
    "Kropyvnytskyy",
    "Kyiv",
    "Luhansk",
    "Lutsk",
    "Lviv",
    "Mykolayiv",
    "Odesa",
    "Poltava",
    "Rivne",
    "Sevastopol",
    "Sumy",
    "Ternopil",
    "Uzhhorod",
    "Vinnytsya",
    "Zaporizhzhya",
    "Zhytomyr",
    "Other",
  ],
  "United Arab Emirates": [
    "Abu Dhabi",
    "Ajman",
    "Dubai",
    "Fujairah",
    "Ras Al Khaimah",
    "Sharjah",
    "Umm Al Quwain City",
    "Other",
  ],
  "United Kingdom": [
    "Belfast",
    "Cardiff",
    "Edinburgh",
    "London",
    "Other",
  ],
  "United States": [
    "Albany",
    "Annapolis",
    "Atlanta",
    "Augusta",
    "Austin",
    "Baton Rouge",
    "Bismarck",
    "Boise",
    "Boston",
    "Carson City",
    "Charleston",
    "Cheyenne",
    "Columbia",
    "Columbus",
    "Concord",
    "Denver",
    "Des Moines",
    "Dover",
    "Frankfort",
    "Harrisburg",
    "Hartford",
    "Helena",
    "Honolulu",
    "Indianapolis",
    "Jackson",
    "Jefferson City",
    "Juneau",
    "Lansing",
    "Lincoln",
    "Little Rock",
    "Madison",
    "Montgomery",
    "Nashville",
    "Oklahoma City",
    "Olympia",
    "Phoenix",
    "Providence",
    "Raleigh",
    "Richmond",
    "Sacramento",
    "Saint Paul",
    "Salem",
    "Salt Lake City",
    "Santa Fe",
    "Springfield",
    "Tallahassee",
    "Topeka",
    "Trenton",
    "Washington",
    "Other",
  ],
  "United States Minor Outlying Islands": [
    "Other",
    "Other",
  ],
  "Uruguay": [
    "Artigas",
    "Canelones",
    "Colonia del Sacramento",
    "Durazno",
    "Florida",
    "Fray Bentos",
    "Maldonado",
    "Melo",
    "Mercedes",
    "Minas",
    "Montevideo",
    "Paysandú",
    "Rivera",
    "Rocha",
    "Salto",
    "San José de Mayo",
    "Tacuarembó",
    "Treinta y Tres",
    "Trinidad",
    "Other",
  ],
  "Uzbekistan": [
    "Andijon",
    "Bukhara",
    "Fergana",
    "Guliston",
    "Jizzax",
    "Namangan",
    "Navoiy",
    "Nukus",
    "Qarshi",
    "Samarkand",
    "Tashkent",
    "Tirmiz",
    "Urganch",
    "Other",
  ],
  "Vanuatu": [
    "Port-Vila",
    "Other",
  ],
  "Vatican": [
    "Vatican City",
    "Other",
  ],
  "Venezuela": [
    "Barcelona",
    "Barinas",
    "Barquisimeto",
    "Caracas",
    "Ciudad Bolívar",
    "Coro",
    "Cumaná",
    "Guanare",
    "La Asunción",
    "La Guaira",
    "Los Teques",
    "Maracaibo",
    "Maracay",
    "Maturín",
    "Mérida",
    "Puerto Ayacucho",
    "San Carlos",
    "San Cristóbal",
    "San Felipe",
    "San Fernando de Apure",
    "San Juan de los Morros",
    "Trujillo",
    "Tucupita",
    "Valencia",
    "Other",
  ],
  "Vietnam": [
    "Bắc Ninh",
    "Bến Tre",
    "Biên Hòa",
    "Buôn Ma Thuột",
    "Cà Mau",
    "Cần Thơ",
    "Cao Bằng",
    "Cao Lãnh",
    "Ðà Lạt",
    "Da Nang",
    "Dien Bien Phu",
    "Ðông Hà",
    "Đồng Xoài",
    "Gia Nghĩa",
    "Hạ Long",
    "Hà Tĩnh",
    "Haiphong",
    "Hanoi",
    "Huế",
    "Hưng Yên",
    "Lai Châu",
    "Lạng Sơn",
    "Lào Cai",
    "Long Xuyên",
    "Mỹ Tho",
    "Nam Định",
    "Ngã Năm",
    "Nha Trang",
    "Ninh Bình",
    "Phan Rang-Tháp Chàm",
    "Phan Thiết",
    "Phủ Lý",
    "Pleiku",
    "Quảng Ngãi",
    "Qui Nhon",
    "Rạch Giá",
    "Sóc Trăng",
    "Sơn La",
    "Tam Kỳ",
    "Tân An",
    "Tây Ninh",
    "Thái Nguyên",
    "Thanh Hóa",
    "Thành Phố Bà Rịa",
    "Thành phố Trà Vinh",
    "Thủ Dầu Một",
    "Tuy Hòa",
    "Tuyên Quang",
    "Vị Thanh",
    "Việt Trì",
    "Vinh",
    "Vĩnh Long",
    "Other",
  ],
  "Wallis and Futuna": [
    "Mata-Utu",
    "Other",
  ],
  "Western Sahara": [
    "Dakhla",
    "Laayoune",
    "Other",
  ],
  "Yemen": [
    "‘Amrān",
    "Aden",
    "Al Bayda",
    "Al Ḩazm",
    "Al Ḩudaydah",
    "Ataq",
    "Dhamār",
    "Ḩajjah",
    "Ibb",
    "Laḩij",
    "Ma'rib",
    "Mukalla",
    "Sa'dah",
    "Sanaa",
    "Taiz",
    "Zinjibār",
    "Other",
  ],
  "Zambia": [
    "Chinsali",
    "Chipata",
    "Choma",
    "Kabwe",
    "Kasama",
    "Lusaka",
    "Mansa",
    "Mongu",
    "Ndola",
    "Solwezi",
    "Other",
  ],
  "Zimbabwe": [
    "Bindura",
    "Bulawayo",
    "Chinhoyi",
    "Gwanda",
    "Gweru",
    "Harare",
    "Marondera",
    "Masvingo",
    "Mutare",
    "Other",
  ],
};

export function getCitiesForCountry(country: string | null): string[] {
  if (!country?.trim()) return [];
  return FULFILLMENT_CITIES_BY_COUNTRY[country.trim()] ?? ["Other"];
}