project_id = "sehxgspdsvderseyvdmz"

[functions.stripe-webhook]
verify_jwt = false

[functions.signup-gmail-no-verify]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.clear-pending-plan]
verify_jwt = false

[functions.brand-create-user]
verify_jwt = false