// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL ?? "").trim();
const SUPABASE_PUBLISHABLE_KEY = (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? "").trim();

const isPlaceholder = (v: string) => !v || v === "placeholder-key" || v.includes("placeholder") || v.includes("buraya_project_ref");
/** Giriş/kayıt öncesi kontrol: .env veya Vercel ortam değişkenlerinde URL ve anon key tanımlı mı? */
export const isSupabaseConfigured =
  !isPlaceholder(SUPABASE_URL) &&
  !isPlaceholder(SUPABASE_PUBLISHABLE_KEY) &&
  SUPABASE_URL.startsWith("https://") &&
  SUPABASE_URL.includes("supabase.co");

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL || "https://placeholder.supabase.co", SUPABASE_PUBLISHABLE_KEY || "placeholder-key", {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});